@startuml
autonumber "<b>[00]"

participant "SustainHub" as SUS
participant "Company A" as COMPA
participant "Company B" as COMPB
participant "Operator" as OP
participant "Blockchain" as BC


== Issue New Product ==

-> SUS: add product data
SUS -> COMPA: send product data
COMPA -> COMPA: store product data
COMPA -> OP: anounce new product\n(id, uid, name, type, number, hash)
OP -> BC: issue new product data\n(id, uid, name, type, number, hash)
BC -> COMPB: notify new product (id, uid, name, type, number, hash)
|||

== Request Product Details ==

COMPB -> OP: request product details\n(uid, pubKeyB, algorithm)
OP -> BC: issue product details request\n(uid, pubKeyB, algorithm)
BC -> COMPA: notify product details request (uid, pubKeyB, algorithm)
COMPA -> COMPA: get product data
COMPA -> COMPA: encrypt(product data, pubKeyB)
COMPA -> OP: send encrypted product data
OP -> COMPB: forward encrypted product data
COMPB -> COMPB: decrypt product data
COMPB -> COMPB: hash product data
COMPB -> COMPB: validate hashes

@enduml