version: "3.8"
networks: 
  operator-network:
    external: false
services:
  operator:
    image: dibichain-operator
    networks:
      - operator-network
    ports:
      # extern:intern
      - 3000:3000
    environment:
      - GREETER_CONTRACT_ADDRESS=0x7fddbf846a115f5708ad1a186fc22540c62395db
      - RPC_URL=http://host.docker.internal:8546
      - MONGO_DB_URL=mongodb://blktrc-backend-db:27017
  operator-db:
    image: mongo:4.4.1-bionic
    networks:
      - blktrc-network
    volumes:
      - ./../data:/data/db