version: "3.8"
networks: 
  dibichain-ganache-network:
    external: false
services:
  dibichain-ganache:
    image: trufflesuite/ganache-cli
    networks: 
      - dibichain-ganache-network
    ports:
      # extern:intern
      - 8546:8545
    command: 
      --db database
      --chainId 4243
      --networkId 100
      --gasLimit 0x2FEFD800000
      --mnemonic "leopard cinnamon bleak insect fragile excuse rib chapter must announce roof focus"
      # --blockTime 15
    volumes:
      - ../database:/app/database

# blockscout -> https://github.com/blockscout/blockscout/tree/master/docker-compose
  dibichain-explorer-db:
    image: postgres:13.6
    networks: 
      - dibichain-ganache-network
    restart: always
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432

  dibichain-explorer:
    depends_on:
      - dibichain-explorer-db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    networks: 
      - dibichain-ganache-network
    restart: always
    links:
      - dibichain-explorer-db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'ganache'
        ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8546/
        ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8546/
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
        DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
        ECTO_USE_SSL: "false"
    ports:
      - 4000:4000