version: "3.8"
networks:
  logistex-network:
    external: false
services:
  logistex-backend:
    image: ghcr.io/chainstep/dibichain/company-backend:demo-latest
    depends_on:
      - logistex-backend-db
    networks:
      - logistex-network
    ports:
      # extern:intern
      - 3000:3000
    environment:
      - MONGO_DB_URL=mongodb://logistex-backend-db:27017
  logistex-backend-db:
    image: mongo:4.4.1-bionic
    networks:
      - logistex-network
    volumes:
      - ./../data:/data/db