version: "3.8"
networks:
  logistly-network:
    external: false
services:
  logistly-client:
    image: ghcr.io/chainstep/dibichain/company-client:demo-latest
    depends_on:
      - logistly-client-db
    networks:
      - logistly-network
    ports:
      # extern:intern
      - 3100:3000
    environment:
      - MONGO_DB_URL=mongodb://logistly-client-db:27017
  logistly-client-db:
    image: mongo:4.4.1-bionic
    networks:
      - logistly-network
    volumes:
      - ./../data:/data/db