name: build operator image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - operator/**

env:
  # github config
  SOURCE_DIR: operator
  
  # docker config
  IMAGE_NAME: operator
  IMAGE_TAG: demo-latest
  REGISTRY_NAME: ghcr.io/chainstep/dibichain

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: 16

      - name: Install dependencies
        run: cd ./${{ env.SOURCE_DIR }} && yarn install
    
      - name: Lint project
        run: cd ./${{ env.SOURCE_DIR }} && yarn lint

      - name: Run tests
        run: cd ./${{ env.SOURCE_DIR }} && yarn test
      
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: ./${{ env.SOURCE_DIR }}/node_modules
          key: ${{ github.sha }}

  build-image:
    runs-on: ubuntu-latest
    needs:
      - test-project
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: 16
      
      - name: Restore dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: ./${{ env.SOURCE_DIR }}/node_modules
          key: ${{ github.sha }}

      - name: Build project
        run: cd ./${{ env.SOURCE_DIR }} && yarn build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.SOURCE_DIR }}/docker/Dockerfile
          context: ./${{ env.SOURCE_DIR }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}