name: build image

on:
  workflow_call:
    inputs:
      project_dir:
        type: string
        required: true
      registry_name:
        type: string
        required: true
      image_name:
        type: string
        required: true
      version:
        type: string
        required: false

env:
  LATEST_TAG: latest

jobs:
  build-image:
    runs-on: ubuntu-latest
    needs:
      - test-project
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set image tags
        run: |
          echo "IMAGE_TAG=${{ inputs.registry_name }}/${{ inputs.image_name }}:${{ env.LATEST_TAG }}" >> $GITHUB_ENV
          if [ "${{ inputs.version }}" != "" ]; then
            echo "RELEASE_IMAGE_TAG=${{ inputs.registry_name }}/${{ inputs.image_name }}:${{ inputs.version }}" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./${{ inputs.project_dir }}/docker/Dockerfile
          context: ./${{ inputs.project_dir }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}
            ${{ env.RELEASE_IMAGE_TAG }}