name: build operator image

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        type: string
        required: false
  push:
    branches:
      - main
    paths:
      - packages/operator/**

env:
  # github config
  PROJECT_DIR: packages/operator
  
  # docker config
  IMAGE_NAME: operator
  REGISTRY_NAME: ghcr.io/chainstep/dibichain
  LATEST_TAG: latest

jobs:
  test-project:
    uses: ./.github/workflows/test-operator.yml
    secrets: inherit

  build-image:
    runs-on: ubuntu-latest
    needs:
      - test-project
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set image tags
        run: |
          echo "IMAGE_TAG=${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}" >> $GITHUB_ENV
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            echo "RELEASE_IMAGE_TAG=${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.PROJECT_DIR }}/docker/Dockerfile
          context: ./${{ env.PROJECT_DIR }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}
            ${{ env.RELEASE_IMAGE_TAG }}