name: create release images

on:
  release:
    types:
      - published

jobs:
  test-company-client:
    uses: ./.github/workflows/test-project.yml
    secrets: inherit
    with:
      project_dir: packages/company-client

  test-company-frontend:
    uses: ./.github/workflows/test-project.yml
    secrets: inherit
    with:
      project_dir: packages/company-frontend
  
  test-operator:
    uses: ./.github/workflows/test-project.yml
    secrets: inherit
    with:
      project_dir: packages/operator

  build-company-client:
    needs:
      - test-company-client
      - test-company-frontend
      - test-operator
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      project_dir: packages/company-client
      registry_name: ghcr.io/chainstep/dibichain
      image_name: company-client
      version: ${{ github.event.release.tag_name }}

  build-company-frontend:
    needs:
      - test-company-client
      - test-company-frontend
      - test-operator
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      project_dir: packages/company-frontend
      registry_name: ghcr.io/chainstep/dibichain
      image_name: company-frontend
      version: ${{ github.event.release.tag_name }}

  build-operator:
    needs:
      - test-company-client
      - test-company-frontend
      - test-operator
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      project_dir: packages/operator
      registry_name: ghcr.io/chainstep/dibichain
      image_name: operator
      version: ${{ github.event.release.tag_name }}