name: create release images

on:
  release:
    types:
      - published

env:
  REGISTRY_NAME: ghcr.io/chainstep/dibichain
  
  CLIENT_PROJECT_DIR: packages/company-client
  CLIENT_IMAGE_NAME: company-client

  FRONTEND_PROJECT_DIR: packages/company-frontend
  FRONTEND_IMAGE_NAME: company-frontend

  OPERATOR_PROJECT_DIR: packages/operator
  OPERATOR_IMAGE_NAME: operator

jobs:
  test-company-client:
    uses: ./.github/workflows/test-project.yml
    secrets: inherit
    with:
      project_dir: ${{ env.CLIENT_PROJECT_DIR }}

  test-company-frontend:
    uses: ./.github/workflows/test-project.yml
    secrets: inherit
    with:
      project_dir: ${{ env.FRONTEND_PROJECT_DIR }}
  
  test-operator:
    uses: ./.github/workflows/test-project.yml
    secrets: inherit
    with:
      project_dir: ${{ env.OPERATOR_PROJECT_DIR }}

  build-company-client:
    needs:
      - test-company-client
      - test-company-frontend
      - test-operator
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      project_dir: ${{ env.CLIENT_PROJECT_DIR }}
      registry_name: ${{ env.REGISTRY_NAME }}
      image_name: ${{ env.CLIENT_IMAGE_NAME }}
      version: ${{ github.event.release.tag_name }}

  build-company-frontend:
    needs:
      - test-company-client
      - test-company-frontend
      - test-operator
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      project_dir: ${{ env.FRONTEND_PROJECT_DIR }}
      registry_name: ${{ env.REGISTRY_NAME }}
      image_name: ${{ env.FRONTEND_IMAGE_NAME }}
      version: ${{ github.event.release.tag_name }}

  build-operator:
    needs:
      - test-company-client
      - test-company-frontend
      - test-operator
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      project_dir: ${{ env.OPERATOR_PROJECT_DIR }}
      registry_name: ${{ env.REGISTRY_NAME }}
      image_name: ${{ env.OPERATOR_IMAGE_NAME }}
      version: ${{ github.event.release.tag_name }}