name: populate default products

on:
  workflow_dispatch:
  workflow_call:

env:
  # github config
  DEPLOY_BRANCH: main

  # server config
  LOGISTEX_DOMAIN: api.logistex.dibichain.de

jobs: 
  populate:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if [ ${BRANCH} != ${{ env.DEPLOY_BRANCH }} ]; then
            echo "Action only works on branch: ${{ env.DEPLOY_BRANCH }}"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v2

      - name: Populate logistex
        run: |
          curl --location --request POST 'https://api.logistex.dibichain.de/my-products' --header 'Content-Type: application/json' --data-raw '{"amount":"1","amountUnit":"each","carbonFootprint":"45","carbonFootprintUnit":"kg","documents":["8181c8ae-eef1-4703-8498-2cf25be2877b"],"name":"Scalmalloy Part","number":"AP12345","type":"purchase_part","weight":"200","weightUnit":"g"}'
          DOCUMENT="{\"myDocuments\": [$(cat ./resources/Carbon_Footprint_Report_Scalmalloy_AP12345.json)]}"
          curl --location --request POST 'https://api.logistex.dibichain.de/my-documents' --header 'Content-Type: application/json' --data-raw "${DOCUMENT}"