name: populate default products

on:
  workflow_dispatch:
  workflow_call:

env:
  # github config
  DEPLOY_BRANCH: main

  # server config
  LOGISTEX_DOMAIN: api.logistex.dibichain.de
  LOGISTLY_DOMAIN: api.logistly.dibichain.de

jobs: 
  populate:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if [ ${BRANCH} != ${{ env.DEPLOY_BRANCH }} ]; then
            echo "Action only works on branch: ${{ env.DEPLOY_BRANCH }}"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: 16

      - name: Populate logistex
        run: |
          node ./resources/productAdder.js ${{ env.LOGISTEX_DOMAIN }} ./resources/products/scalmalloy-part/scalmalloy-part.json
          node ./resources/documentAdder.js ${{ env.LOGISTEX_DOMAIN }} 8181c8ae-eef1-4703-8498-2cf25be2877b ./resources/products/scalmalloy-part/Carbon_Footprint_Report_Scalmalloy_AP12345.pdf
      
      - name: Populate logistly
        run: |
          node ./resources/productAdder.js ${{ env.LOGISTLY_DOMAIN }} ./resources/products/bionic-partition/bionic-partition.json