name: test company client

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - packages/company-client/**

env:
  PROJECT_DIR: packages/company-client

jobs:
  test-company-client:
    uses: ./.github/workflows/test-project.yml
    secrets: inherit
    with:
      project_dir: ${{ env.PROJECT_DIR }}