name: test company frontend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - packages/company-frontend/**

env:
  PROJECT_DIR: packages/company-frontend

jobs:
  test-company-frontend:
    uses: ./.github/workflows/test-project.yml
    secrets: inherit
    with:
      project_dir: ${{ env.PROJECT_DIR }}