name: test operator

on:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - packages/operator/**

env:
  # github config
  PROJECT_DIR: packages/operator

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd ./${{ env.PROJECT_DIR }}
          yarn install
    
      - name: Lint project
        run: |
          cd ./${{ env.PROJECT_DIR }}
          yarn lint

      - name: Run tests
        run: |
          cd ./${{ env.PROJECT_DIR }}
          yarn test