name: test and build company frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/company-frontend/**

env:
  PROJECT_DIR: packages/company-frontend
  REGISTRY_NAME: ghcr.io/chainstep/dibichain
  IMAGE_NAME: company-frontend

jobs:
  test-company-frontend:
    uses: ./.github/workflows/test-project.yml
    secrets: inherit
    with:
      project_dir: ${{ env.PROJECT_DIR }}

  build-company-frontend:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      project_dir: ${{ env.PROJECT_DIR }}
      registry_name: ${{ env.REGISTRY_NAME }}
      image_name: ${{ env.IMAGE_NAME }}
