name: test project

on:
  workflow_call:
    inputs:
      project_dir:
        required: true
        type: string

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd ./${{ inputs.project_dir }}
          yarn install
    
      - name: Lint project
        run: |
          cd ./${{ inputs.project_dir }}
          yarn lint

      - name: Run tests
        run: |
          cd ./${{ inputs.project_dir }}
          yarn test