name: test company backend

on:
  push:
    branches:
      - main
    paths:
      - company-backend/**

env:
  SOURCE_DIR: company-backend

jobs:
  test-company-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: cd ./${{ env.SOURCE_DIR }} && yarn install
    
    - name: Lint
      run: cd ./${{ env.SOURCE_DIR }} && yarn lint

    - name: Run tests
      run: cd ./${{ env.SOURCE_DIR }} && yarn test

    - name: Build company backend
      run: cd ./${{ env.SOURCE_DIR }} && yarn build