name: test operator

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - packages/operator/**

env:
  PROJECT_DIR: packages/operator

jobs:
  test-operator:
    uses: ./.github/workflows/test-project.yml
    secrets: inherit
    with:
      project_dir: ${{ env.PROJECT_DIR }}