name: test company client

on:
  pull_request:
    branches:
      - main
    paths:
      - company-client/**

env:
  # github config
  SOURCE_DIR: company-client

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: 16

      - name: Install dependencies
        run: cd ./${{ env.SOURCE_DIR }} && yarn install
    
      - name: Lint project
        run: cd ./${{ env.SOURCE_DIR }} && yarn lint

      - name: Run tests
        run: cd ./${{ env.SOURCE_DIR }} && yarn test